### ISSUE TITLE
Validation for End Dates that are Earlier than Start Dates [Event]

### ISSUE THREAD

**Issue by joeng03** [NUS-Fintech-Society/Atlas_2#152]
**Describe the bug**
Users are able to create events that have an end date that is earlier than start date.

**To Reproduce**
1. Go to http://localhost:3000/events
2. Click the 'Create Event' button
3. Create an event with end date earlier than start date.

**Expected behavior**
When creating an event, the system should validate against end dates that are earlier than start dates.

**Screenshots**
![image](https://github.com/NUS-Fintech-Society/Atlas_2/assets/51855281/8a9765e5-84f1-48d3-b475-50bd0e5b75f3)

**Comment by craigtonlian** [comment]
Closed with #154
