### ISSUE TITLE
Create Event Page

### ISSUE THREAD

**Issue by woowenjun99** [NUS-Fintech-Society/Atlas_2#68]
**Describe the bug**
- [x] There's 2 department fields in the create new event page
- [x] Colour of table in create new event page is wrong

**Comment by loyhongshenggg** [comment]
![image](https://user-images.githubusercontent.com/97422591/227086629-365b42bb-33c7-42b5-aeb0-3cdc8d609470.png)
![image](https://user-images.githubusercontent.com/97422591/227086651-a81bbbe2-0e9b-4436-89d5-08eb43578dc8.png)
